name = "MutatePlainDataArray"
uuid = "3b0f367b-da20-4531-811a-c13cc92422b5"
authors = ["Haoran Ni <haoranni@terpmail.umd.edu> and contributors"]
version = "0.4.0"

[compat]
julia = "1.7"

[workspace]
projects = ["test"]
